-- +goose Up

CREATE TABLE branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_code VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(150) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

CREATE TABLE service (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code VARCHAR(50)  NOT NULL UNIQUE,
    service_name VARCHAR(150) NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

CREATE TABLE sales_agent (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT       NOT NULL,
    employee_id VARCHAR(50)  NOT NULL UNIQUE,
    agent_name  VARCHAR(150) NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,

    CONSTRAINT fk_sales_agent_branch
        FOREIGN KEY (branch_id)
        REFERENCES branch (id)
);

CREATE TABLE counter (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    BIGINT       NOT NULL,
    counter_code VARCHAR(50)  NOT NULL UNIQUE,
    counter_name VARCHAR(100) NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,

    CONSTRAINT fk_counter_branch
        FOREIGN KEY (branch_id)
        REFERENCES branch (id)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name     VARCHAR(50) NOT NULL UNIQUE,
    sales_agent_id BIGINT      NOT NULL,
    status        VARCHAR(20) NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,

    CONSTRAINT fk_users_sales_agent
        FOREIGN KEY (sales_agent_id)
        REFERENCES sales_agent (id)
);

CREATE TABLE counter_assignment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counter_id   BIGINT    NOT NULL,
    sales_agent_id BIGINT  NOT NULL,
    assigned_at  TIMESTAMP NOT NULL,
    unassigned_at TIMESTAMP,
    status       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,

    CONSTRAINT fk_counter_assignment_counter
        FOREIGN KEY (counter_id)
        REFERENCES counter (id),

    CONSTRAINT fk_counter_assignment_sales_agent
        FOREIGN KEY (sales_agent_id)
        REFERENCES sales_agent (id)
);

CREATE TABLE queue (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_date    DATE         NOT NULL,
    queue_number  VARCHAR(20)  NOT NULL,
    branch_id     BIGINT       NOT NULL,
    service_id    BIGINT       NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(30) NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,

    CONSTRAINT fk_queue_branch
        FOREIGN KEY (branch_id)
        REFERENCES branch (id),

    CONSTRAINT fk_queue_service
        FOREIGN KEY (service_id)
        REFERENCES service (id)
);

CREATE TABLE queue_handling (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id      BIGINT      NOT NULL,
    sales_agent_id BIGINT     NOT NULL,
    counter_id    BIGINT      NOT NULL,
    start_time    TIMESTAMP   NOT NULL,
    end_time      TIMESTAMP,
    status        VARCHAR(20) NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,

    CONSTRAINT fk_queue_handling_queue
        FOREIGN KEY (queue_id)
        REFERENCES queue (id),

    CONSTRAINT fk_queue_handling_sales_agent
        FOREIGN KEY (sales_agent_id)
        REFERENCES sales_agent (id),

    CONSTRAINT fk_queue_handling_counter
        FOREIGN KEY (counter_id)
        REFERENCES counter (id)
);

-- Indexes for foreign keys / common lookups

CREATE INDEX idx_sales_agent_branch_id
    ON sales_agent (branch_id);

CREATE INDEX idx_counter_branch_id
    ON counter (branch_id);

CREATE INDEX idx_users_sales_agent_id
    ON users (sales_agent_id);

CREATE INDEX idx_counter_assignment_counter_id
    ON counter_assignment (counter_id);

CREATE INDEX idx_counter_assignment_sales_agent_id
    ON counter_assignment (sales_agent_id);

CREATE INDEX idx_queue_branch_id
    ON queue (branch_id);

CREATE INDEX idx_queue_service_id
    ON queue (service_id);

CREATE INDEX idx_queue_handling_queue_id
    ON queue_handling (queue_id);

CREATE INDEX idx_queue_handling_sales_agent_id
    ON queue_handling (sales_agent_id);

CREATE INDEX idx_queue_handling_counter_id
    ON queue_handling (counter_id);


-- +goose Down

DROP TABLE IF EXISTS queue_handling;
DROP TABLE IF EXISTS counter_assignment;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS queue;
DROP TABLE IF EXISTS counter;
DROP TABLE IF EXISTS sales_agent;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS branch;
